/*CRIAÇÃO BANCO DE DADOS*/
CREATE DATABASE SVIGUFO;

-- USAR O BANCO DE DADDOS CRIADO --
USE SVIGUFO;


-- CRIAR TABELA TIPO DE EVENTO 
CREATE TABLE TIPOS_EVENTOS (
	ID INT IDENTITY PRIMARY KEY
	,TITULO VARCHAR(250) UNIQUE NOT NULL
);

--TABELA INSTITUIÇOES 

CREATE TABLE INSTITUICOES(
	ID INT IDENTITY PRIMARY KEY 
	,NOME_FANTASIA VARCHAR(250) NULL
	,RASAO_SOCIAL VARCHAR(250) NOT NULL
	,CNPJ CHAR(14) NOT NULL UNIQUE 
	,LOGRADOURO VARCHAR(250) NOT NULL
	,CEP CHAR(8) NOT NULL
	,UF CHAR(2) NOT NULL
	,CIDADE VARCHAR(200) NOT NULL

);

CREATE TABLE EVENTOS (
	ID INT IDENTITY PRIMARY KEY
	,TITULO VARCHAR(250) NOT NULL
	,DESCRICAO TEXT NOT NULL
	,DATA_EVENTO DATETIME NOT NULL 
	,ACESSO_LIVRE BIT DEFAULT (1)
	-- 1 ACESSO PUBLICO, 0 ACESSO RESTRITO
	,ID_INSTITUICAO INT 
	,ID_TIPO_EVENTO INT 
	-- DEFINE AS CHAVES ESTRANGEIRAS 
	,FOREIGN KEY (ID_INSTITUICAO) REFERENCES INSTITUICOES(ID)
	,FOREIGN KEY (ID_TIPO_EVENTO) REFERENCES TIPOS_EVENTOS(ID)
);

CREATE TABLE USUARIOS(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(250) NOT NULL
	,EMAIL VARCHAR(250) NOT NULL UNIQUE
	,SENHA VARCHAR(100) NOT NULL
	,TIPO_USUARIO VARCHAR(50) NOT NULL
	);

CREATE TABLE CONVITES(
	ID INT IDENTITY PRIMARY KEY
	,ID_USUARIO INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(ID)
	,ID_EVENTO INT NOT NULL FOREIGN KEY REFERENCES EVENTOS(ID)
	,SITUACAO CHAR(1) DEFAULT(1)
);
